[providers]
python = {}

[phases.install]
cmds = ["pip3 install -r careertracker/requirements.txt"]

[phases.build]
cmds = [
  "cd careertracker && python3 manage.py migrate"
]

[start]
cmd = "cd careertracker && gunicorn careertracker.wsgi --bind 0.0.0.0:${PORT:-8000} --log-file -"
