[providers]
python = {}

[phases.install]
cmds = ["pip3 install -r requirements.txt"]

[phases.build]
cmds = [
  "python3 manage.py migrate"
]

[start]
cmd = "gunicorn careertracker.wsgi --bind 0.0.0.0:$PORT --log-file -"
